num1_input = input("Give me the first number: ")
num2_input = input("Give me the second number ")
num1 = int(num1_input)
num2 = int(num2_input)
print("Thank you")
print(f"{num1} + {num2} = {num1 + num2}")
print(f"{num1} - {num2} = {num1 - num2}")
print(f"{num1} / {num2} = {num1 // num2}")
print(f"{num1} * {num2} = {num1 * num2}")
